Algoritmo "semnome"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2023
Var
// Seção de Declarações das variáveis 
i, n, f:inteiro
Inicio
f <- 1
escreval ("escreva um numero")
leia (n)
para i de n ate 1 passo -1 faca
f <- f*i
escreval (f)
escreval ("fatorial de: ", n, " é", f)
fimpara
Fimalgoritmo