Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/08/2023
Var
// Seção de Declarações das variáveis 
N1, N2 , N3, M: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
ESCREVA ("nota 1: ")
leia (n1)
ESCREVA ("nota 2: ")
leia (n2)
ESCREVA ("nota 3: ")
leia (n3)
M <- (N1*2+N2*3+N3*5)/10
ESCREVAL ("Média: ", M)
Fimalgoritmo