Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/08/2023
Var
// Seção de Declarações das variáveis
alt: real
homem: real
mulher: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("digite sua altura: ")
leia (alt)

homem <- 72.7*alt - 58
mulher <- 62.1*alt - 44.7

escreval ("homem: ", homem)
escreval ("mulher: ", mulher)

Fimalgoritmo

