Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/08/2023
Var
// Seção de Declarações das variáveis 
base: inteiro
altura: inteiro
multi: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva(" base: ")
leia(base)
escreva(" altura: ")
leia(altura)
multi <- base*altura
escreva(" multi ", multi )

Fimalgoritmo