Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/08/2023
Var
// Seção de Declarações das variáveis 
metros: inteiro
cm: inteiro
val: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva(" metros: ")
leia(metros)
escreval(" considere cm igual 100 ", cm)
escreva(" cm: ")
leia(cm)
val <- metros*cm
escreval(" val: ", val)

Fimalgoritmo