Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/08/2023
Var
// Seção de Declarações das variáveis 
mb: inteiro
mbps: inteiro
min: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva(" mb: ")
leia(mb)
escreva(" mbps: ")
leia(mbps)
min <- (mb/(mbps/8))/60
escreval(" min: ", min)
Fimalgoritmo